pipeline {
    agent any
    environment{
        COMMIT_HASH = sh(returnStdout: true, script: "git rev-parse --short=8 HEAD").trim()
    }
    stages{
        stage('Terraform plan'){
            steps{
                dir("terraform"){
                    sh "terraform init"
                    sh "terraform plan -destroy -out destroyplan.tf-${COMMIT_HASH}"
                }
            }
        }
        stage('Terraform destroy'){
            steps{
                dir("terraform"){
                    sh "terraform apply --auto-approve destroyplan.tf-${COMMIT_HASH}"
                    echo "done!"
                }

            }
        }
    }
}