version: '2'
services:
    flights:
        image: jswen19109814/flight:flight
        ports: 
        - '9001'
        depends_on:
            - "users"
        environment:
            - MYSQL_DB_HOST=utopia.cztkke9ur9zz.us-east-2.rds.amazonaws.com
            - MYSQL_DB_PORT=3306
            - MYSQL_DB_SCHEMA=jwutopia
            - MYSQL_DB_USERNAME=admin
            - MYSQL_DB_PASSWORD=09132021SmoothStack!
            - USERS_MS_URL=http://users:9002/user
    users:
        image: jswen19109814/user:user
        ports: 
        - '9002'
        container_name: users
        environment:
            - MYSQL_DB_HOST=utopia.cztkke9ur9zz.us-east-2.rds.amazonaws.com
            - MYSQL_DB_PORT=3306
            - MYSQL_DB_SCHEMA=jwutopia
            - MYSQL_DB_USERNAME=admin
            - MYSQL_DB_PASSWORD=09132021SmoothStack!
        logging:
            driver: "awslogs"
            options:
                awslogs-region: "us-east-2"
                awslogs-group: "jw-utopia"
                awslogs-stream-prefix: "docker-compose-ecs-stream"
    bookings:
        image: jswen19109814/booking:booking
        ports: 
        - '9003'
        depends_on:
            - "users"
        environment:
            - MYSQL_DB_HOST=utopia.cztkke9ur9zz.us-east-2.rds.amazonaws.com
            - MYSQL_DB_PORT=3306
            - MYSQL_DB_SCHEMA=jwutopia
            - MYSQL_DB_USERNAME=admin
            - MYSQL_DB_PASSWORD=09132021SmoothStack!
            - USERS_MS_URL=http://users:9002/user
                    
            