pipeline {
    agent any
    environment{
        COMMIT_HASH = sh(returnStdout: true, script: "git rev-parse --short=8 HEAD").trim()
        DESTROY = false
    }
    stages{
        stage('Terraform plan'){
            steps{
                sh "terraform init"
                sh "terraform plan -out plan.tf-${COMMIT-HASH}"
            }
        }
        // stage('Terraform destroy'){
        //     steps{
        //         sh "terraform destroy --auto-approve"
        //         echo "done!"
        //     }
        // }
        stage('Terraform apply'){
            steps{
                sh "terraform apply --auto-approve plan.tf-${COMMIT-HASH}"
                echo "done!"
            }
        }
    }
}