pipeline {
    agent any
    environment{
        COMMIT_HASH = sh(returnStdout: true, script: "git rev-parse --short=8 HEAD").trim()
    }
    stages{
        stage('Terraform plan'){
            steps{
                dir("terraform"){
                    sh "dir"
                    sh "terraform init"
                    sh "terraform plan -out plans/plan-${COMMIT_HASH}.tf -no-color > plans/plan-${COMMIT_HASH}.txt"
                    //need to scan the document here 
                    script{
                        env.CHECK_LINE = sh "tail -n 1 plans/plan-${COMMIT_HASH}.txt"
                        env.CHECK_LINE = "test value"
                        echo ${CHECK_LINE}
                    }
                }
            }
        }
        stage('Terraform apply'){
            steps{
                dir("terraform"){
                    sh "terraform apply --auto-approve -no-color plans/plan-${COMMIT_HASH}.tf"
                }
            }
        }
    }
}