version: '2'
services:
    flights:
        image: ${ECR_FLIGHT}
        ports: 
        - '9001'
        depends_on:
            - "users"
        environment:
            - MYSQL_DB_HOST=utopia.cztkke9ur9zz.us-east-2.rds.amazonaws.com
            - MYSQL_DB_PORT=3306
            - MYSQL_DB_SCHEMA=jwutopia
            - MYSQL_DB_USERNAME=admin
            - MYSQL_DB_PASSWORD=09132021SmoothStack!
            - USERS_MS_URL=http://users:9002/user
            - SERVER_PORT=9001
        logging:
            driver: "awslogs"
            options:
                awslogs-region: "us-east-2"
                awslogs-group: "jw-utopia-flights"
                awslogs-stream-prefix: "docker-compose-ecs-stream"
    users:
        image: ${ECR_USER}
        ports: 
        - '9002'
        container_name: users
        environment:
            - MYSQL_DB_HOST=utopia.cztkke9ur9zz.us-east-2.rds.amazonaws.com
            - MYSQL_DB_PORT=3306
            - MYSQL_DB_SCHEMA=jwutopia
            - MYSQL_DB_USERNAME=admin
            - MYSQL_DB_PASSWORD=09132021SmoothStack!
            - SERVER_PORT=9002
        logging:
            driver: "awslogs"
            options:
                awslogs-region: "us-east-2"
                awslogs-group: "jw-utopia-users"
                awslogs-stream-prefix: "docker-compose-ecs-stream"
    bookings:
        image: ${ECR_BOOKING}
        ports: 
        - '9003'
        depends_on:
            - "users"
        environment:
            - MYSQL_DB_HOST=utopia.cztkke9ur9zz.us-east-2.rds.amazonaws.com
            - MYSQL_DB_PORT=3306
            - MYSQL_DB_SCHEMA=jwutopia
            - MYSQL_DB_USERNAME=admin
            - MYSQL_DB_PASSWORD=09132021SmoothStack!
            - USERS_MS_URL=http://users:9002/user
            - SERVER_PORT=9003
        logging:
            driver: "awslogs"
            options:
                awslogs-region: "us-east-2"
                awslogs-group: "jw-utopia-bookings"
                awslogs-stream-prefix: "docker-compose-ecs-stream"
            