pipeline {
    agent any
    stages {
        stage('Docker build') {
            steps {
                dir("docker"){
                    echo 'Running docker-compose: '
                    sh 'docker-compose up'
                }
            }
        }
    }
}