apiVersion: v1
kind: Service
metadata:
  name: booking
spec:
  ports:
  - port: 9003
  selector:
    app: booking
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
spec:
  selector:
    matchLabels:
      app: booking
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
      - image: jswen19109814/booking:booking
        name: booking
        imagePullPolicy: Always
        env: 
        - name: MYSQL_DB_HOST
          value: "mysql"
        - name: MYSQL_DB_PORT
          value: "3306"
        - name: MYSQL_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: USERS_MS_URL
          value: "http://users:9002/user"
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: MYSQL_DB_SCHEMA
          value: "utopia"
        
        ports:
        - containerPort: 9003
          name: booking