apiVersion: v1
kind: Service
metadata:
  name: booking
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app.kubernetes.io/name: booking
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: booking
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: booking
    spec:
      containers:
      - image: jswen19109814/booking:booking
        imagePullPolicy: Always
        env: 
        - name: SERVER_PORT
          value: "80"
        - name: MYSQL_DB_HOST 
          value: "utopia.cztkke9ur9zz.us-east-2.rds.amazonaws.com"
        - name: MYSQL_DB_PORT
          value: "3306"
        - name: MYSQL_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: MYSQL_DB_SCHEMA
          value: "jwutopia"
        - name: USERS_MS_URL
          value:  "http://user:80/user"
        name: booking
        ports:
        - containerPort: 80