apiVersion: v1
kind: Service
metadata:
  name: flight
spec:
  ports:
  - port: 9001
  selector:
    app: flight
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight
spec:
  selector:
    matchLabels:
      app: flight
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flight
    spec:
      containers:
      - image: jswen19109814/flight:flight
        name: flight
        imagePullPolicy: Always
        env: 
        - name: MYSQL_DB_HOST
          value: "mysql"
        - name: MYSQL_DB_PORT
          value: "3306"
        - name: MYSQL_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: USERS_MS_URL
          value: "http://users:9002/user"
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: MYSQL_DB_SCHEMA
          value: "utopia"
        
        ports:
        - containerPort: 9001
          name: flight