 - name: ec2create
   hosts: localhost
   connection: local
   gather_facts: False
   tags: provisioning

   vars:
     keypair: jw-key-pem
     instance_type: t2.micro
     image:  ami-064ff912f78e3e561
     wait: yes
     group: webserver
     count: 1
     region: us-east-2
     security_group: testSecGroup
   
   tasks:
     - name: Create my security group
       local_action: 
         module: ec2_group
         name: "{{ security_group }}"
         description: Security Group for webserver Servers
         region: "{{ region }}"
         rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 9000
              to_port: 9000
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
         rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
       register: basic_firewall


     - name: Launch the new EC2 Instance
       local_action:  ec2 
                      group={{ security_group }} 
                      instance_type={{ instance_type}} 
                      image={{ image }} 
                      wait=true 
                      region={{ region }} 
                      keypair={{ keypair }}
                      count={{count}}
       register: ec2


     - name: Add Tagging to EC2 instance
       local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
       with_items: "{{ ec2.instances }}"
       args:
         tags:
           Name: testansible
           type: jwansible
    

     - name: ec2 instance info
       debug: 
         msg: "{{ec2.instances[0].public_ip}}"
    
     - name: Add to route 53
        community.aws.route53:
         state: present
         zone: hitec.link
         record: ansiblejw.hitec.link
         type: A
         value: {{ec2.instances[0].public_ip}}



       
